# Display Dimensions
display_width: 600
display_height: 448

# Hardware Profile (generic or spectra_e6)
hardware: generic

latitude: 51.5074
longitude: -0.1278
server_ip: 192.168.1.18
weather_provider: smhi
icon_provider_display: openweathermap
icon_provider_graph: meteomatics
temperature_unit: C
icon_provider_list:
- openweathermap
- google
- meteomatics
supplemental_providers:
- provider_name: open-meteo
  parameters:
  - uvi
- provider_name: AQICN
  parameters:
  - aqi
  - aqi_pm25_avg
provider_list:
- open-meteo
- openweathermap
- meteomatics
- google
- smhi
parameter_list:
- temp
- feels_like
- humidity
- uvi
- wind_speed
- wind_deg
- wind_gust
- rain
- snow
google_api_key: YOUR_GOOGLE_API_KEY_HERE
openweathermap_api_key: YOUR_OPENWEATHERMAP_API_KEY_HERE
meteomatics_username: YOUR_METEOMATICS_USERNAME_HERE
meteomatics_password: YOUR_METEOMATICS_PASSWORD_HERE
aqicn_api_token: YOUR_AQICN_TOKEN_HERE
current_weather_display_details:
- feels_like
- humidity
- wind_speed
- aqi
daily_forecast_display_details:
- temp
- rain
- wind
- uvi
cache_duration_minutes: 10
graph_24h_forecast_config:
  base_font_size: 12
  y_axis_label_font_weight: bold
  x_axis_tick_font_weight: bold
  y_axis_tick_font_weight: bold
  show_y_grid_left: false
  show_y_grid_right: true
  graph_time_range_hours: 48
  day_night_highlight:
    enabled: true
    color: lightgrey
    alpha: 0.6
    mode: civil_twilight
  x_axis_hour_interval: 6
  x_axis_time_format: '%H'
  x_axis_tick_rotation: 0
  legend:
    standard_legend:
      enabled: false
      position: bottom
      columns: 3
      fontsize: 9
      font_weight: bold
      frame_on: true
      frame_alpha: 0.6
      frame_face_color: white
      frame_edge_color: darkgrey
    peak_value_display:
      enabled: true
      location: in_graph
      layering: in_front
      axis_start_anchor_y: 0.97
      horizontal_alignment: right
      vertical_alignment_per_line: top
      font_size: 10
      font_weight: bold
      axis_line_y_step: 0.085
      text_bbox:
        enabled: false
        face_color: white
        alpha: 0.75
        edge_color: none
        boxstyle: round,pad=0.3
  wind_arrows:
    enabled: true
    parameter_speed: wind_speed
    parameter_degrees: wind_deg
    color: darkgreen
    edge_color: black
    size: 12
  series:
  - parameter: temp
    axis_label: Temp. (C)
    legend_label: ''
    axis_label_side: left
    axis: right
    color: '#FF6347'
    color_negative: '#1E90FF'
    line_style: solid
    linewidth: 3
    show_y_axis_ticks: true
    show_y_axis_tick_labels: true
    y_axis_integer_ticks: false
    scale_type: auto_padded
    data_occupancy_factor: 0.8
    weather_symbols:
      enabled: true
      prefer_day_owm_icons: false
      icon_size_pixels: 20
      vertical_offset_pixels: 10
      time_interval_hours: 4
  - parameter: wind_speed
    axis_label: ''
    legend_label: Wind
    axis: left
    color: '#32CD32'
    show_peak_in_legend: true
    unit: m/s
    line_style: solid
    linewidth: 1.5
    show_y_axis_ticks: false
    show_y_axis_tick_labels: false
    scale_type: manual_range
    y_axis_min: 0
    y_axis_max: 25
  - parameter: wind_gust
    axis_label: ''
    legend_label: ''
    axis: left
    color: '#32CD32'
    show_peak_in_legend: false
    unit: m/s
    line_style: dashed
    linewidth: 0.1
    show_y_axis_ticks: false
    show_y_axis_tick_labels: false
    scale_type: manual_range
    y_axis_min: 0
    y_axis_max: 25
  - plot_type: fill_between_two_series
    series1_param_name: wind_speed
    series2_param_name: wind_gust
    color: lightgreen
    alpha: 0.4
    zorder: 1.8
  - parameter: rain
    axis_label: ''
    legend_label: Rain
    axis: left
    color: '#1E90FF'
    show_peak_in_legend: true
    unit: mm
    plot_type: fill_between
    alpha: 0.4
    linewidth: 1
    show_y_axis_ticks: false
    show_y_axis_tick_labels: false
    scale_type: manual_range
    y_axis_min: 0.01
    y_axis_max: 2
icon_configs:
  daily_display:
    google:
      width: 60
      height: 60
      x_offset: 0
      y_offset: 20
    openweathermap:
      width: 100
      height: 100
      x_offset: -12
      y_offset: 5
    meteomatics:
      width: 85
      height: 85
      x_offset: -12
      y_offset: 5
    default:
      width: 80
      height: 80
      x_offset: -10
      y_offset: 10
  current_display:
    google:
      width: 80
      height: 80
      x_offset: 0
      y_offset: 35
    openweathermap:
      width: 100
      height: 100
      x_offset: -15
      y_offset: 35
    meteomatics:
      width: 100
      height: 100
      x_offset: -15
      y_offset: 35
    default:
      width: 90
      height: 90
      x_offset: -10
      y_offset: 40
  graph_icons:
    google_scale_factor: 0.6
    openweathermap_scale_factor: 1.0
    meteomatics_scale_factor: 1.0
    default_scale_factor: 1.0
mqtt_broker: 192.168.0.111
mqtt_port: 1883
mqtt_user: homeassistant
mqtt_password: ''
